server:
  port: 9903
spring:
  application:
    name: find-person-with-car
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orclpdb1
    username: ****
    password: ****
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9001/eureka}
